version: '2'
services:

 bookieapi:
  image: pbsa/bookieapi:1.0
  environment:
   - 'DEFAULT_ACCOUNT=1.2.18'
  ports:
   - "0.0.0.0:5051:5051"
  volumes:
  - "bookieapi:/var/lib/bookieapi"

volumes:
 bookieapi:
